name: Auto Commit Every Minute

on:
  schedule:
    - cron: "*/1 * * * *" # Ejecutar cada minuto
  workflow_dispatch: # Permitir ejecución manual

jobs:
  auto-commit:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Auto Commit Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Auto commit $(date)"
          git push
