name: Auto Commit Every Minute

on:
  schedule:
    - cron: "*/1 * * * *" # Ejecutar cada minuto
  workflow_dispatch: # Permitir ejecución manual

jobs:
  auto-commit:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # Usa el token secreto

      - name: Auto Commit Changes
        shell: pwsh # Usa PowerShell
        run: |
          git config --global user.name "v019-exe"
          git config --global user.email "v019-exe@example.com"
          git add -A
          if (-not (git diff-index --quiet HEAD)) {
            git commit -m "Auto commit $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
            git push
          }
