name: Auto Commit Every Minute

on:
  schedule:
    - cron: "*/5 * * * *" # Ejecutar cada 5 minutos
  workflow_dispatch: # Permitir ejecución manual

jobs:
  auto-commit:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # Usa el token secreto

      - name: Modify File Randomly
        shell: powershell # Usa Windows PowerShell
        run: |
          $filePath = "random_file.txt" # Nombre del archivo
          if (-not (Test-Path $filePath)) {
            Set-Content -Path $filePath -Value "." # Crea el archivo si no existe
          } else {
            Add-Content -Path $filePath -Value "." # Agrega un punto al archivo
          }

      - name: Pull Remote Changes (if any)
        shell: powershell # Usa Windows PowerShell
        run: |
          git config --global user.name "v019-exe"
          git config --global user.email "v019-exe@example.com"
          git pull origin main # Trae los cambios del repositorio remoto

      - name: Auto Commit Changes
        shell: powershell # Usa Windows PowerShell
        run: |
          git add -A
          if (-not (git diff-index --quiet HEAD)) {
            git commit -m "Auto commit $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
            git push
          }
